name: Flask Application CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest
        
    - name: Run tests
      run: |
        python -m pytest tests/ -v

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Deploy to PythonAnywhere
      env:
        PYTHONANYWHERE_TOKEN: ${{ secrets.PYTHONANYWHERE_TOKEN }}
        USERNAME: ${{ secrets.PYTHONANYWHERE_USERNAME }}
      run: |
        # Install PythonAnywhere CLI
        pip install pythonanywhere

        # Update the code on PythonAnywhere
        pa_autoconfigure_django.py --python=3.10 \
          --nuke \
          https://github.com/${{ github.repository }}
